import type { NextPage } from 'next';
import Head from 'next/head';
import ItemCard from '../components/ItemCard';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto min-h-screen p-4'>
				<h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700 text-center'>
					<span className='text-purple-300'>Happi Clothing</span>
				</h1>
				<div className='flex gap-8 flex-wrap px-12'>
					<ItemCard
						title='Nike Air Forces'
						description='hi is very nice'
						price={100}
					/>
					<ItemCard
						title='Nike Air Forces'
						description='hi is very nice'
						price={100}
					/>
					<ItemCard
						title='Nike Air Forces'
						description='hi is very nice'
						price={100}
					/>
					<ItemCard
						title='Nike Air Forces'
						description='hi is very nice'
						price={100}
					/>
					<ItemCard
						title='Nike Air Forces'
						description='hi is very nice'
						price={100}
					/>
				</div>
			</main>
		</>
	);
};

export default Home;
